version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/phpvegas
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - phpvegas-network

  php:
    build: ./
    volumes:
      - ./:/phpvegas
    networks:
      - phpvegas-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - phpvegas-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - phpvegas-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phpvegas
      MYSQL_USER: phpvegas
      MYSQL_PASSWORD: rocks
    volumes:
      - /Docker/mysql-data:/var/lib/mysql

networks:
  phpvegas-network:
    driver: bridge